import type { TAvailableFavoriteMenu } from '../../homepage/homepage.declaration';

export type TIconType = 'mat' | 'svg';

export type TMenu = {
  path: string;
  localizationKey: string;
  id: TAvailableFavoriteMenu;
  icon: string;
  iconType: TIconType;
  permission: string;
  favorable: boolean;
  children?: Omit<TMenu, 'id' | 'favorable'>[];
};

export const menus: TMenu[] = [
  { path: 'home', localizationKey: 'ERP_072.Home Page', id: 'home', icon: 'dashboard', iconType: 'mat', permission: '', favorable: true },
  {
    path: 'candidates',
    localizationKey: 'Admissions',
    id: 'candidate',
    icon: 'account-arrow-right',
    iconType: 'svg',
    permission: 'candidate.show_perm',
    favorable: true,
    children: [
      {
        path: 'candidates',
        localizationKey: 'NAV.Follow up FI',
        icon: 'account-arrow-right',
        iconType: 'svg',
        permission: 'candidate.show_perm',
      },
      {
        path: 'candidates-fc',
        localizationKey: 'NAV.Follow up FC',
        icon: 'account-arrow-right',
        iconType: 'svg',
        permission: 'candidate.follow_up_continuous.show_perm',
      },
      {
        path: 'contract-follow-up',
        localizationKey: 'Follow up Contract/Convention',
        icon: 'account-arrow-right',
        iconType: 'svg',
        permission: 'candidate.follow_up_contract.show_perm',
      },
      {
        path: 'oscar-campus',
        localizationKey: 'NAV.CRM Oscar Campus',
        icon: 'account-settings',
        iconType: 'svg',
        permission: 'candidate.oscar_campus.show_perm',
      },
      {
        path: 'hubspot',
        localizationKey: 'NAV.CRM Hubspot',
        icon: 'account-settings',
        iconType: 'svg',
        permission: 'candidate.hubspot.show_perm',
      },
      {
        path: 'dashboard-register',
        localizationKey: 'NAV.DASHBOARDS.General',
        icon: 'dashboard',
        iconType: 'mat',
        permission: 'candidate.candidate_dashboard.show_perm',
      },
    ],
  },
  {
    path: 'assignment',
    localizationKey: 'NAV.Re-Admission',
    id: 'readmission',
    icon: 'account-sync-outline',
    iconType: 'svg',
    permission: 'readmission.show_perm',
    favorable: true,
    children: [
      {
        path: 'assignment',
        localizationKey: 'NAV.Assignment',
        icon: 'pencil-ruler',
        iconType: 'svg',
        permission: 'readmission.assignment.show_perm',
      },
      {
        path: 'follow-up',
        localizationKey: 'NAV.Follow up',
        icon: 'account-arrow-right',
        iconType: 'svg',
        permission: 'readmission.follow_up.show_perm',
      },
    ],
  },
  {
    path: 'students-table',
    localizationKey: 'NAV.Students',
    id: 'students',
    icon: 'school',
    iconType: 'mat',
    permission: 'students.show_perm',
    favorable: true,
    children: [
      {
        path: 'students-table',
        localizationKey: 'NAV.STUDENT.Registered',
        icon: 'account-arrow-right',
        iconType: 'svg',
        permission: 'students.follow_up.show_perm',
      },
      {
        path: 'all-students',
        localizationKey: 'NAV.STUDENT.All students',
        icon: 'groups',
        iconType: 'mat',
        permission: 'students.all_students.show_perm',
      },
      {
        path: 'students-trombinoscope',
        localizationKey: 'NAV.STUDENT.Trombinoscope',
        icon: 'account_box',
        iconType: 'mat',
        permission: 'students.trombinoscope.show_perm',
      },
    ],
  },
  {
    path: 'finance-follow-up',
    localizationKey: 'Finance',
    id: 'finance',
    icon: 'euro',
    iconType: 'mat',
    permission: 'finance.show_perm',
    favorable: true,
    children: [
      {
        path: 'finance-follow-up',
        localizationKey: 'NAV.FINANCE.Follow Up',
        icon: 'euro',
        iconType: 'mat',
        permission: 'finance.follow_up.show_perm',
      },
      {
        path: 'finance-follow-up-organization',
        localizationKey: 'NAV.FINANCE.Follow Up Organization',
        icon: 'euro',
        iconType: 'mat',
        permission: 'finance.follow_up_organization.show_perm',
      },
      {
        path: 'operation-lines',
        localizationKey: 'NAV.FINANCE.Operations Lines',
        icon: 'scale-balance',
        iconType: 'svg',
        permission: 'finance.operation_lines.show_perm',
      },
      {
        path: 'unbalanced-balance',
        localizationKey: 'NAV.FINANCE.Unbalanced Balance',
        icon: 'scale-unbalanced',
        iconType: 'svg',
        permission: 'finance.unbalanced_balance.show_perm',
      },
      {
        path: 'timeline-template',
        localizationKey: 'NAV.FINANCE.Timeline template',
        icon: 'event_busy',
        iconType: 'mat',
        permission: 'finance.timeline_template.show_perm',
      },
      {
        path: 'transaction-report',
        localizationKey: 'NAV.Transaction',
        icon: 'euro',
        iconType: 'mat',
        permission: 'finance.transaction_report.show_perm',
      },
      {
        path: 'master-transaction',
        localizationKey: 'NAV.Master Transaction',
        icon: 'euro',
        iconType: 'mat',
        permission: 'finance.master_table_transaction.show_perm',
      },
      {
        path: 'balance-report',
        localizationKey: 'NAV.Balance Report',
        icon: 'euro',
        iconType: 'mat',
        permission: 'finance.balance_report.show_perm',
      },
    ],
  },
  {
    path: 'teacher-management',
    localizationKey: 'NAV.Teacher Management',
    id: 'teacher_management',
    icon: 'account-edit-outline',
    iconType: 'svg',
    permission: 'teacher_management.show_perm',
    favorable: true,
    children: [
      {
        path: 'teacher-management/follow-up',
        localizationKey: 'NAV.Follow up',
        icon: 'account-edit-outline',
        iconType: 'svg',
        permission: 'teacher_management.teacher_follow_up.show_perm',
      },
      {
        path: 'teacher-management/teachers',
        localizationKey: 'NAV.Teachers',
        icon: 'account-edit-outline',
        iconType: 'svg',
        permission: 'teacher_management.teachers_table.show_perm',
      },
      {
        path: 'teacher-contract/contract-management',
        localizationKey: 'NAV.TEACHER_CONTRACT.CONTRACT_MANAGEMENT',
        icon: 'text-box-check',
        iconType: 'svg',
        permission: 'teacher_management.contract_process.show_perm',
      },
    ],
  },
  {
    path: 'alumni-follow-up',
    localizationKey: 'Alumni',
    id: 'alumni',
    icon: 'group',
    iconType: 'mat',
    permission: 'alumni.show_perm',
    favorable: true,
    children: [
      {
        path: 'alumni-follow-up',
        localizationKey: 'NAV.alumni-follow-up',
        icon: 'group',
        iconType: 'mat',
        permission: 'alumni.follow_up.show_perm',
      },
      { path: 'alumni-cards', localizationKey: 'NAV.alumni-cards', icon: 'group', iconType: 'mat', permission: 'alumni.card.show_perm' },
    ],
  },
  {
    path: 'companies',
    localizationKey: 'NAV.COMPANIES',
    id: 'companies',
    icon: 'business',
    iconType: 'mat',
    permission: 'companies.show_perm',
    favorable: true,
    children: [
      {
        path: 'companies/entities',
        localizationKey: 'NAV.Companies Entity',
        icon: 'companies',
        iconType: 'svg',
        permission: 'companies.company_entity.show_perm',
      },
      {
        path: 'companies/branches',
        localizationKey: 'NAV.Companies Branches',
        icon: 'companies',
        iconType: 'svg',
        permission: 'companies.company_branch.show_perm',
      },
      {
        path: 'organization',
        localizationKey: 'NAV.Organization',
        icon: 'database-marker-outline',
        iconType: 'svg',
        permission: 'companies.organization.show_perm',
      },
    ],
  },
  {
    path: 'form-follow-up',
    localizationKey: 'NAV.Form Follow Up',
    id: 'form_follow_up',
    icon: 'content_paste_search',
    iconType: 'svg',
    permission: 'form_follow_up.show_perm',
    favorable: true,
    children: [
      {
        path: 'form-follow-up/general-form-follow-up',
        localizationKey: 'NAV.General Form Follow Up',
        icon: 'content_paste_search',
        iconType: 'svg',
        permission: 'form_follow_up.general_form_follow_up.show_perm',
      },
    ],
  },
  {
    path: 'task',
    localizationKey: 'NAV.MYTASKS',
    id: 'tasks',
    icon: 'clipboard-list-outline',
    iconType: 'svg',
    permission: 'tasks.show_perm',
    favorable: true,
  },
  {
    path: 'mailbox',
    localizationKey: 'NAV.MAILBOX',
    id: 'mailbox',
    icon: 'mail',
    iconType: 'mat',
    permission: 'mailbox.show_perm',
    favorable: true,
  },
  {
    path: 'history',
    localizationKey: 'NAV.HISTORY.NAME',
    id: 'history',
    icon: 'format_list_bulleted',
    iconType: 'mat',
    permission: 'history.show_perm',
    favorable: true,
    children: [
      {
        path: 'notifications',
        localizationKey: 'NAV.HISTORY.NOTIFICATIONS',
        icon: 'folder-alert',
        iconType: 'svg',
        permission: 'history.notifications.show_perm',
      },
    ],
  },
  {
    path: 'template-sequences',
    localizationKey: 'course_sequence.Courses & Sequences',
    id: 'courses_sequences',
    icon: 'login',
    iconType: 'svg',
    permission: 'courses_sequences.show_perm',
    favorable: true,
    children: [
      {
        path: 'template-sequences',
        localizationKey: 'course_sequence.Template',
        icon: 'pencil-ruler',
        iconType: 'svg',
        permission: 'courses_sequences.template.show_perm',
      },
      {
        path: 'sequences',
        localizationKey: 'course_sequence.Sequences',
        icon: 'clipboard-list-outline',
        iconType: 'svg',
        permission: 'courses_sequences.sequence.show_perm',
      },
      {
        path: 'modules',
        localizationKey: 'course_sequence.Modules',
        icon: 'clipboard-list-outline',
        iconType: 'svg',
        permission: 'courses_sequences.module.show_perm',
      },
      {
        path: 'subjects',
        localizationKey: 'course_sequence.Subjects',
        icon: 'clipboard-list-outline',
        iconType: 'svg',
        permission: 'courses_sequences.subject.show_perm',
      },
    ],
  },
  {
    path: 'users',
    localizationKey: 'NAV.USERS',
    id: 'users',
    icon: 'person',
    iconType: 'mat',
    permission: 'users.show_perm',
    favorable: true,
  },
  {
    path: 'schools',
    localizationKey: 'NAV.INTAKE_CHANNEL.Intake channel',
    id: 'intake_channel',
    icon: 'login',
    iconType: 'svg',
    permission: 'intake_channel.show_perm',
    favorable: true,
    children: [
      {
        path: 'scholar-season',
        localizationKey: 'NAV.INTAKE_CHANNEL.Scholar season',
        icon: 'calendar-blank-multiple',
        iconType: 'svg',
        permission: 'intake_channel.scholar_season.show_perm',
      },
      {
        path: 'schools',
        localizationKey: 'NAV.INTAKE_CHANNEL.Schools',
        icon: 'account_balance',
        iconType: 'mat',
        permission: 'intake_channel.school.show_perm',
      },
      {
        path: 'campus',
        localizationKey: 'NAV.INTAKE_CHANNEL.Campus',
        icon: 'town-hall',
        iconType: 'svg',
        permission: 'intake_channel.campus.show_perm',
      },
      {
        path: 'level',
        localizationKey: 'NAV.INTAKE_CHANNEL.Level',
        icon: 'order-numeric-ascending',
        iconType: 'svg',
        permission: 'intake_channel.level.show_perm',
      },
      {
        path: 'sector',
        localizationKey: 'NAV.INTAKE_CHANNEL.Sector',
        icon: 'work',
        iconType: 'mat',
        permission: 'intake_channel.sector.show_perm',
      },
      {
        path: 'speciality',
        localizationKey: 'NAV.INTAKE_CHANNEL.Speciality',
        icon: 'book-education-outline',
        iconType: 'svg',
        permission: 'intake_channel.speciality.show_perm',
      },
      {
        path: 'site',
        localizationKey: 'NAV.INTAKE_CHANNEL.Sites',
        icon: 'location_on',
        iconType: 'mat',
        permission: 'intake_channel.site.show_perm',
      },
      {
        path: 'settings',
        localizationKey: 'NAV.INTAKE_CHANNEL.Settings',
        icon: 'settings',
        iconType: 'mat',
        permission: 'intake_channel.setting.show_perm',
      },
    ],
  },
  {
    path: 'import-register',
    localizationKey: 'NAV.SETTINGS.Settings',
    id: 'setting',
    icon: 'settings',
    iconType: 'mat',
    permission: 'setting.show_perm',
    favorable: true,
    children: [
      {
        path: 'import-register',
        localizationKey: 'NAV.SETTINGS.Import of Registration Objectives',
        icon: 'file-excel',
        iconType: 'svg',
        permission: 'setting.import_objective.show_perm',
      },
      {
        path: 'import-finance',
        localizationKey: 'NAV.SETTINGS.Import of financial objectives',
        icon: 'file-excel',
        iconType: 'svg',
        permission: 'setting.import_objective_finance.show_perm',
      },
      {
        path: 'import-previous-finance',
        localizationKey: 'NAV.SETTINGS.Import of financial N - 1',
        icon: 'file-excel',
        iconType: 'svg',
        permission: 'setting.import_finance_n1.show_perm',
      },
      {
        path: 'promo-external',
        localizationKey: 'NAV.SETTINGS.External promotions',
        icon: 'bullhorn',
        iconType: 'svg',
        permission: 'setting.external_promotion.show_perm',
      },
      {
        path: 'step-validation-message',
        localizationKey: 'NAV.SETTINGS.Messages Steps',
        icon: 'check-underline-circle',
        iconType: 'svg',
        permission: 'setting.message_step.show_perm',
      },
      {
        path: 'notification-management',
        localizationKey: 'NAV.PROCESS.NOTIFICATION_MANAGEMENT',
        icon: 'clipboard-flow',
        iconType: 'svg',
        permission: 'setting.notification_management.show_perm',
      },
      {
        path: 'user-permission',
        localizationKey: 'NAV.SETTINGS.USER_PERMISSION',
        icon: 'settings',
        iconType: 'mat',
        permission: 'setting.user_permission.show_perm',
      },
      {
        path: 'country-nationality',
        localizationKey: 'NAV.SETTINGS.COUNTRY_NATIONALITY',
        icon: 'flag',
        iconType: 'svg',
        permission: 'setting.show_perm',
      },
    ],
  },
  {
    path: 'process',
    localizationKey: 'NAV.PROCESS.NAME',
    id: 'process',
    icon: 'ship-wheel',
    iconType: 'svg',
    permission: 'process.show_perm',
    favorable: true,
    children: [
      {
        path: 'form-builder',
        localizationKey: 'NAV.PROCESS.FORM_BUILDER',
        icon: 'pencil-ruler',
        iconType: 'svg',
        permission: 'process.form_builder.show_perm',
      },
      {
        path: 'document-builder',
        localizationKey: 'Documents',
        icon: 'file-document-plus-outline',
        iconType: 'svg',
        permission: 'process.document.show_perm',
      },
    ],
  },
  {
    path: 'tutorial',
    localizationKey: 'NAV.TUTORIALS',
    id: 'tutorials',
    icon: 'human-male-board',
    iconType: 'svg',
    permission: 'tutorials.tutorial_table',
    favorable: true,
  },
  {
    path: 'tutorial-app',
    localizationKey: 'InApp Tutorials',
    id: 'inapp_tutorials',
    icon: 'human-male-board',
    iconType: 'svg',
    permission: 'tutorials.inapp_tutorials.show_perm',
    favorable: true,
  },
  {
    path: 'news',
    localizationKey: 'NAV.News',
    id: 'news',
    icon: 'script-text-outline',
    iconType: 'svg',
    permission: 'news.show_perm',
    favorable: true,
    children: [
      {
        path: 'news/all-news',
        localizationKey: 'NAV.All News',
        icon: 'assignment',
        iconType: 'mat',
        permission: 'news.all_news.show_perm',
      },
      {
        path: 'news/manage-news',
        localizationKey: 'NAV.Manage News',
        icon: 'file-document-plus-outline',
        iconType: 'svg',
        permission: 'news.manage_news.show_perm',
      },
    ],
  },
];
